### ISSUE TITLE
YSF 

### ISSUE THREAD

**Issue by astro-debug** [ZantetsukenGT/AttDef#6]
(fatal) cannot read from file: "YSF"
Build encountered fatal error

#include <YSF>
#if !defined _YSF_included
	#include <omp>		 // omp's native YSF implementations
#endif

**Comment by ZantetsukenGT** [comment]
I deliberately broke the main branch since at the time it was being used for PWAC and the codebase was based on open.mp, but PWAC was made for samp, so i had to introduce some breaking changes and I didn't commit the complete changes into the remote branch.

The issues you reported should be gone and the code can be compiled again, using open.mp beta 11, in the future i might introduce omp-stdlib and use the latest omp version, I still don't know when I will do this.
